name: player
description: Player API function for Fortify.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.7

dependencies:
  core:
    path: packages/core
  infrastructure:
    path: packages/infrastructure
  dart_appwrite: ^13.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
