name: database
description: Database setup CLI - creates AppWrite collections, attributes, and indexes.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.7

dependencies:
  core:
    path: ../../packages/core
  dart_appwrite: ^13.0.0
  dotenv: ^4.2.0

dev_dependencies:
  lints: ^6.0.0
