name: core
description: Shared domain models, interfaces, enums, and use cases.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.7

dependencies:
  get_it: ^7.6.0
  equatable: ^2.0.5

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  mockito: ^5.4.0
  build_runner: ^2.3.3
